language: python
    
python: "3.6"
    
git:
  depth: 1

install:
  - pip install codecov

script: 
  - python -m unittest discover -p "fraction_test.py"
  - coverage run fraction_test.py

after_success:
  - codecov